# Useful Python Commands

## General Info

### Imports

In [61]:
import numpy as np
from numpy import linalg as la
import scipy as sp

This gives us access to the numpy library. We can use it with the prefix np. We then import the linear algebra library from numpy. This is not necessary to make use of it, but it makes it easier to access it. We finally will bring in the scipy library which gives us expm() and log(m).

### Numpy and Linalg

Python doesn't care much about column and row vectors the way matlab does.  It will throw errors if you don't do things the way it wants, but you can do things that don't make mathematical sense.

### Lists and Arrays

In [62]:
A = [1, 2, 3]  # These are lists
B = [4, 5, 6]

print(A+B)

C = np.array([1, 2, 3])  # These are lists
D = np.asarray(B)

print(C+D)

[1, 2, 3, 4, 5, 6]
[5 7 9]


### Important to note how python deals with variable asignments

In [63]:
A = np.array([1, 2, 3])
B = A

print(A)
print(B)

[1 2 3]
[1 2 3]


In [64]:
A[1] = 5

print(A)
print(B)

[1 5 3]
[1 5 3]


In Python, when you asign one variable to another variable, it does not make copy of that variable, it just points to or links to the same object.  Thus when you change A, you also change B.  To make a copy, we need to make a copy or deep copy.

### Copy and Deepcopy

In [65]:
# importing copy module 
import copy 
  
# initializing list 1  
list1 = [4, 5, [0,2], 7, 8, 9] 
  
  
# using copy for shallow copy   
list2 = copy.copy(list1)  
  
# using deepcopy for deepcopy   
list3 = copy.deepcopy(list1) 

print("Original List")
print(list1)
print("Shallow copy")
print(list2)
print("Deep copy")
print(list3)




Original List
[4, 5, [0, 2], 7, 8, 9]
Shallow copy
[4, 5, [0, 2], 7, 8, 9]
Deep copy
[4, 5, [0, 2], 7, 8, 9]


They appear all the same, but we should see what happens when we change elements at different levels.

In [66]:
list1[0] = 4
list1[2][1] = 8
print("Original List")
print(list1)
print("Shallow copy after changing elements in both the main list and the sub-list")
print(list2)
print("Deep copy after changing elements in both the main list and the sub-list")
print(list3)

Original List
[4, 5, [0, 8], 7, 8, 9]
Shallow copy after changing elements in both the main list and the sub-list
[4, 5, [0, 8], 7, 8, 9]
Deep copy after changing elements in both the main list and the sub-list
[4, 5, [0, 2], 7, 8, 9]


We can see that with the shallow copy, ths sub list is still linked to the first list.  It only copies the first level which means it only links to the second level objects.  The deep copy fully copies all levels of the object.  This takes more time, so should only be used when needed.  A shallow copy is fine when you only have one level to start with.

## Lab 4

### Cross products

In [67]:
a = [1, 2, 3]
b = [4, 5, 6]

print(np.cross(a,b))

[-3  6 -3]


In [68]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

print(np.cross(a,b, axis=0))

[[-3]
 [ 6]
 [-3]]


In [69]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.cross(a,b))

[-3  6 -3]


In [70]:
a = np.array([[1], [2], [3]]).T
b = np.array([[4], [5], [6]]).T

print(np.cross(a,b))

[[-3  6 -3]]


### Slicing and Indexing Arrays

In [71]:
A = np.array([[1, 2, 3],\
     [4, 5, 6],\
     [7, 8, 9]])
v = np.array([-1 -2, -3, -4, -5, -6, -7, -8, -9])
u = np.array([[10],[11],[12],[13],[14],[15]])


In [72]:
print(A[1:3,1:3])
print(A[0:3][0:1]) # How does this work???
print(A[1][1])

[[5 6]
 [8 9]]
[[1 2 3]]
5


### Concatinating

In [73]:
R = np.array([[0, 0, 1],\
              [0, 1, 0],\
              [1, 0, 0]])
p = np.array([[-2],[5],[1]])
bottom = np.array([[0, 0 ,0, 1]])
#print(R)
print(p.shape)
print(bottom.shape)

A = np.concatenate((R,p), axis = 1)
print(A.shape)
print(np.concatenate((A,bottom)))


(3, 1)
(1, 4)
(3, 4)
[[ 0  0  1 -2]
 [ 0  1  0  5]
 [ 1  0  0  1]
 [ 0  0  0  1]]


In [74]:
A = np.array([[1, 2, 3]])
B = np.array([[4, 5, 6]])
print(np.concatenate((A,B), axis = 1))
print(np.concatenate((A,B), axis = 0))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


### Concatenating Strings

In [75]:
String = 'The UR3 has ' + str(6) + ' DOFs.'
print(String)

The UR3 has 6 DOFs.
