# Useful Python Commands

## General Info

### Imports

In [1]:
import numpy as np
from numpy import linalg as la
import scipy as sp

This gives us access to the numpy library. We can use it with the prefix np. We then import the linear algebra library from numpy. This is not necessary to make use of it, but it makes it easier to access it. We finally will bring in the scipy library which gives us expm() and log(m).

### Numpy and Linalg

Python doesn't care much about column and row vectors the way matlab does.  It will throw errors if you don't do things the way it wants, but you can do things that don't make mathematical sense.

### Lists and Arrays

In [2]:
A = [1, 2, 3]  # These are lists
B = [4, 5, 6]

print(A+B) # This concatenates the lists

C = np.array([1, 2, 3])  # These are numpy arrays
D = np.asarray(B) # This turns a list into a numpy array

print(C+D)

[1, 2, 3, 4, 5, 6]
[5 7 9]


### Important to note how python deals with variable asignments

In [3]:
A = np.array([1, 2, 3])
B = A

print(A)
print(B)

[1 2 3]
[1 2 3]


In [4]:
A[1] = 5

print(A)
print(B)

[1 5 3]
[1 5 3]


In Python, when you asign one variable to another variable, it does not make copy of that variable, it just points to or links to the same object.  Thus when you change A, you also change B.  To make a copy, we need to make a copy or deep copy.

### Copy and Deepcopy

In [5]:
# importing copy module 
import copy 
  
# initializing list 1  
list1 = [4, 5, [0,2], 7, 8, 9] 
  
  
# using copy for shallow copy   
list2 = copy.copy(list1)  
  
# using deepcopy for deepcopy   
list3 = copy.deepcopy(list1) 

print("Original List")
print(list1)
print("Shallow copy")
print(list2)
print("Deep copy")
print(list3)




Original List
[4, 5, [0, 2], 7, 8, 9]
Shallow copy
[4, 5, [0, 2], 7, 8, 9]
Deep copy
[4, 5, [0, 2], 7, 8, 9]


They appear all the same, but we should see what happens when we change elements at different levels.

In [6]:
list1[0] = 4
list1[2][1] = 8
print("Original List")
print(list1)
print("Shallow copy after changing elements in both the main list and the sub-list")
print(list2)
print("Deep copy after changing elements in both the main list and the sub-list")
print(list3)

Original List
[4, 5, [0, 8], 7, 8, 9]
Shallow copy after changing elements in both the main list and the sub-list
[4, 5, [0, 8], 7, 8, 9]
Deep copy after changing elements in both the main list and the sub-list
[4, 5, [0, 2], 7, 8, 9]


We can see that with the shallow copy, ths sub list is still linked to the first list.  It only copies the first level which means it only links to the second level objects.  The deep copy fully copies all levels of the object.  This takes more time, so should only be used when needed.  A shallow copy is fine when you only have one level to start with.

### Printing data

In [7]:
# print integer and float value 
print("Apples: %2d, Kilograms of pears : %5.2f" %(6, 07.1234567)) 

Apples:  6, Kilograms of pears :  7.12


%2d displays an integre value in a space of 2 characters.
%5.2f displays a float value in a space of 5 characters with two of them to the left of the decimal point.
https://www.geeksforgeeks.org/python-output-formatting/ provides more guidance and details.

In [8]:
# using format() method 
print('I ate {} {} for {}!'.format(6.5, 'apples', 'lunch')) 

I ate 6.5 apples for lunch!


## Lab 3: Forward Kinematics

### Cross products

#### Using a list

In [9]:
a = [1, 2, 3]
b = [4, 5, 6]

print(np.cross(a,b))

[-3  6 -3]


#### Using a numpy array as a column vector

In [10]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

print(np.cross(a,b, axis=0)) # Need to declare the axis or you will get an error

[[-3]
 [ 6]
 [-3]]


In [11]:
a = np.array([[1], [2], [3]]).T
b = np.array([[4], [5], [6]]).T

print(np.cross(a,b)) # Using transpose eliminates the need for the axis, but does return an object of a different shape.

[[-3  6 -3]]


#### Using a numpy array as a row vector

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.cross(a,b))

[-3  6 -3]


### Slicing and Indexing Arrays

In [13]:
A = np.array([[1, 2, 3],\
     [4, 5, 6],\
     [7, 8, 9]])
v = np.array([-1 -2, -3, -4, -5, -6, -7, -8, -9])
u = np.array([[10],[11],[12],[13],[14],[15]])


In [14]:
print(A[1:3,1:3])
print(A[0:3][0:1])
print(A[1][1])

[[5 6]
 [8 9]]
[[1 2 3]]
5


### Axis

In [20]:
A = np.array([[1, 2, 3],\
              [1, 2, 3]])
print(A.sum(axis = 0)) # Sums each column i.e. the directions is accross the rows
print(A.sum(axis = 1)) # Sums each row i.e. the directions is accross the columns

[2 4 6]
[6 6]


### Concatenating

In [19]:
R = np.array([[0, 0, 1],\
              [0, 1, 0],\
              [1, 0, 0]])
p = np.array([[-2],[5],[1]])
bottom = np.array([[0, 0 ,0, 1]])
print(R.shape)
print(p.shape)
print(bottom.shape)

A = np.concatenate((R,p), axis = 1) # Joining as columns
print(A.shape)
print(np.concatenate((A,bottom))) # Axis not needed as axis = 0 is the only way it will work


(3, 3)
(3, 1)
(1, 4)
(3, 4)
[[ 0  0  1 -2]
 [ 0  1  0  5]
 [ 1  0  0  1]
 [ 0  0  0  1]]


Shape tells you the number of rows and columns in the array in that order.
If the rows don't match, we can't concatenate along axis 1.
Same for columns, if they don't match we can't concatenate along axis 0.

In [16]:
A = np.array([[1, 2, 3]])
B = np.array([[4, 5, 6]])
print(np.concatenate((A,B), axis = 1))
print(np.concatenate((A,B), axis = 0))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


### Concatenating Strings

In [17]:
String = 'The UR3 has ' + str(6) + ' DOFs.'
print(String)

The UR3 has 6 DOFs.


## Generally useful commands

In [18]:
np.zeros((2,2))
#np.ones((5,3))

array([[0., 0.],
       [0., 0.]])